### ISSUE TITLE
Bugs in notification api update

### ISSUE THREAD

**Issue by SrMouraSilva** [PedalPi/Application#13]
* Add Effect;
* Change effect position;
* add / remove connection.

```
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 22.39ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.27ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.26ms
Traceback (most recent call last):
  File "webservice/handler/effect_handler.py", line 45, in post
    self.controller.created(effect, self.token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/effect_controller.py", line 47, in created
    self._notify_change(effect, UpdateType.CREATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/effect_controller.py", line 82, in _notify_change
    self.notifier.effect_updated(effect, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 92, in effect_updated
    observer.on_effect_updated(effect, update_type, token, **kwargs)
TypeError: on_effect_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 POST /bank/0/pedalboard/1/effect (10.41.18.91) 22.84ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.23ms




Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.34ms


ERROR:tornado.application:Uncaught exception PUT /bank/0/pedalboard/0/connect (10.41.18.52)
HTTPServerRequest(protocol='http', host='10.41.101.20:3000', method='PUT', uri='/bank/0/pedalboard/0/connect', version='HTTP/1.1', remote_ip='10.41.18.52', headers={'User-Agent': 'Mozilla/5.0 (Linux; Android 4.1.2; GT-P3110 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Crosswalk/23.53.589.4 Safari/537.36', 'Host': '10.41.101.20:3000', 'Accept-Language': 'pt-br', 'Origin': 'file://', 'Content-Type': 'text/plain', 'Content-Length': '97', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'X-Xsrf-Token': '63fbae79-6d08-4e6a-b45f-9cf453f7b7f7'})
Traceback (most recent call last):
  File "/home/paulo/Documentos/PedalPi-Raspberry/PedalPi/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "webservice/util/handler_utils.py", line 12, in wrapped
    f(*args, **kwargs)
  File "webservice/handler/connection_handler.py", line 29, in put
    self.controller.connected(pedalboard, connection, token=self.token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/effect_controller.py", line 94, in connected
    self.notifier.connection_updated(pedalboard, connection, UpdateType.CREATED, token=token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 127, in connection_updated
    observer.on_connection_updated(pedalboard, connection, update_type, token)
  File "webservice/websocket/updates_observer_socket.py", line 81, in on_connection_updated
    bank = pedalboard.bank
AttributeError: 'UpdateType' object has no attribute 'bank'
ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/connect (10.41.18.52) 35.25ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.91) 2.31ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.22ms
ERROR:tornado.application:Uncaught exception POST /bank/0/pedalboard/0/disconnect (10.41.18.52)
HTTPServerRequest(protocol='http', host='10.41.101.20:3000', method='POST', uri='/bank/0/pedalboard/0/disconnect', version='HTTP/1.1', remote_ip='10.41.18.52', headers={'User-Agent': 'Mozilla/5.0 (Linux; Android 4.1.2; GT-P3110 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Crosswalk/23.53.589.4 Safari/537.36', 'Host': '10.41.101.20:3000', 'Accept-Language': 'pt-br', 'Origin': 'file://', 'Content-Type': 'text/plain', 'Content-Length': '97', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'X-Xsrf-Token': '63fbae79-6d08-4e6a-b45f-9cf453f7b7f7'})
Traceback (most recent call last):
  File "/home/paulo/Documentos/PedalPi-Raspberry/PedalPi/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "webservice/util/handler_utils.py", line 12, in wrapped
    f(*args, **kwargs)
  File "webservice/handler/connection_handler.py", line 41, in post
    self.controller.disconnected(pedalboard, connection, token=self.token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/effect_controller.py", line 106, in disconnected
    self.notifier.connection_updated(pedalboard, connection, UpdateType.DELETED, token=token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 127, in connection_updated
    observer.on_connection_updated(pedalboard, connection, update_type, token)
  File "webservice/websocket/updates_observer_socket.py", line 81, in on_connection_updated
    bank = pedalboard.bank
AttributeError: 'UpdateType' object has no attribute 'bank'
ERROR:tornado.access:500 POST /bank/0/pedalboard/0/disconnect (10.41.18.52) 4.68ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.36ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.21ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.39ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.34ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.52) 2.38ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.91) 2.35ms
ERROR:tornado.application:Uncaught exception PUT /bank/0/pedalboard/0/connect (10.41.18.91)
HTTPServerRequest(protocol='http', host='10.41.101.20:3000', method='PUT', uri='/bank/0/pedalboard/0/connect', version='HTTP/1.1', remote_ip='10.41.18.91', headers={'User-Agent': 'Mozilla/5.0 (Linux; Android 4.1.1; C1604 Build/11.3.A.3.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Crosswalk/23.53.589.4 Mobile Safari/537.36', 'Host': '10.41.101.20:3000', 'Accept-Language': 'pt-br', 'Origin': 'file://', 'Content-Type': 'text/plain', 'Content-Length': '97', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'X-Xsrf-Token': '137ae190-eb92-4f07-903a-738afe810621'})
Traceback (most recent call last):
  File "/home/paulo/Documentos/PedalPi-Raspberry/PedalPi/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "webservice/util/handler_utils.py", line 12, in wrapped
    f(*args, **kwargs)
  File "webservice/handler/connection_handler.py", line 29, in put
    self.controller.connected(pedalboard, connection, token=self.token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/effect_controller.py", line 94, in connected
    self.notifier.connection_updated(pedalboard, connection, UpdateType.CREATED, token=token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 127, in connection_updated
    observer.on_connection_updated(pedalboard, connection, update_type, token)
  File "webservice/websocket/updates_observer_socket.py", line 81, in on_connection_updated
    bank = pedalboard.bank
AttributeError: 'UpdateType' object has no attribute 'bank'
ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/connect (10.41.18.91) 2.83ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.91) 2.39ms
Traceback (most recent call last):
  File "webservice/handler/pedalboard_data_handler.py", line 46, in put
    self.controller.update(pedalboard, self.token, reload=False)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 76, in update
    self._notify_change(pedalboard, UpdateType.UPDATED, token)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/pedalboard_controller.py", line 176, in _notify_change
    self.notifier.pedalboard_updated(pedalboard, update_type, token, **kwargs)
  File "/home/paulo/Documentos/PedalPi-Raspberry/Application/application/controller/notification_controller.py", line 80, in pedalboard_updated
    observer.on_pedalboard_updated(pedalboard, update_type, token, **kwargs)
TypeError: on_pedalboard_updated() got multiple values for argument 'index'

ERROR:tornado.access:500 PUT /bank/0/pedalboard/0/data/pedalpi-apk (10.41.18.91) 2.30ms
```

**Comment by SrMouraSilva** [comment]
I test in developent and the error has not present. It's necessary push project https://github.com/PedalPi/Application/commit/baa63ca4a4d85a4734c416404b4b6ea3e3f2406d
